import { Router } from 'express';
import ctrl, { getJoueurById, getJoueurHistory, getJoueurPostes, getJoueurSeasonRoster, getJoueurSuggestions, getJoueurTransactionOptions, getJoueurTransactions, getJoueursGrid, getJoueurSeasonsByPlayedMatches, getJoueurMatches } from '../controllers/joueurs.controller';
const router = Router();
router.get('/grid', getJoueursGrid);
router.get('/season-roster/:saison', getJoueurSeasonRoster);
router.get('/postes', getJoueurPostes);
router.get('/suggest', getJoueurSuggestions);
router.get('/:id/history', getJoueurHistory);
router.get('/:id/matches/seasons', getJoueurSeasonsByPlayedMatches);
router.get('/:id/matches/:saison', getJoueurMatches);
router.get('/:id/transactions/options', getJoueurTransactionOptions);
router.get('/:id/transactions', getJoueurTransactions);
router.get('/', ctrl.getAll);
router.get('/:id', getJoueurById);
export default router;
