import { Router } from 'express';
import ctrl, { getCalendar, getOnThisDay, getRencontreDetail, getRencontreHighlights, getTourMatches, getComposition, saveComposition, getSquad, createEvent, updateEvent, deleteEvent, recomputeStats } from '../controllers/rencontres.controller';
const router = Router();
router.get('/calendar', getCalendar);
router.get('/on-this-day', getOnThisDay);
router.get('/:id/detail', getRencontreDetail);
router.get('/:id/highlights', getRencontreHighlights);
router.get('/:id/tour-matches', getTourMatches);
router.get('/:id/composition', getComposition);
router.put('/:id/composition', saveComposition);
router.get('/:id/squad', getSquad);
router.post('/:id/events', createEvent);
router.put('/:id/events/:evid', updateEvent);
router.delete('/:id/events/:evid', deleteEvent);
router.post('/:id/recompute-stats', recomputeStats);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
export default router;
