import { createEntityService } from '../lib/baseService';

export default createEntityService({
  table:           'EQUIPE',
  pk:              'EQCLEUNIK',
  selectCols:      [
    'EQCLEUNIK',
    'DATE',
    'SAISON',
    'GOAL',
    'DLG',
    'DLD',
    'DCG',
    'DCD',
    'LIB',
    'STO',
    'MDLD',
    'MDLG',
    'MDCD',
    'MDCG',
    'MOLD',
    'MOLG',
    'MOCD',
    'MOCG',
    'MOCC',
    'MDCC',
    'ALD',
    'ALG',
    'ACD',
    'ACG',
    'AVC',
    'REMP1',
    'REMP2',
    'REMP3',
    'REMP4',
    'REMP5',
    'REMP6',
    'REMP7',
    'REMP8',
    'REMP9',
    'REMP10',
    'REMP11',
    'ENTRAINEUR',
    'MACLEUNIK',
  ],
  allowedSortCols: ['EQCLEUNIK', 'DATE', 'SAISON'],
  searchCols:      [],
  filterCols:      ['SAISON', 'MACLEUNIK'],
});
