import { Router } from 'express';
import ctrl, { createSaisonWithWizard } from '../../controllers/saisons.controller';
const router = Router();
router.post('/',       ctrl.create);
router.post('/wizard-create', createSaisonWithWizard);
router.put('/:id',    ctrl.update);
router.patch('/bulk', ctrl.bulkUpdate);
router.delete('/bulk', ctrl.bulkDelete);
router.delete('/:id', ctrl.remove);
export default router;
